services:
  - type: web
    name: jarvis-metas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8256513003:AAHfpBECsu1qaJiKhdE5i3eFWB32AOI_ZDY
      - key: TELEGRAM_CHAT_ID
        value: 8428346208
